/***************************************************************
        Modelling tool
    Delete History, Freeze Transforms, Center Pivot
        By Julian Beiboer
    
****************************************************************/
{
    $selection = `ls -sl`;
    for($object in $selection)
    {
        delete -ch;
        makeIdentity -apply true -t 1 -r 1 -s 1 -n 0;
        xform -cp;
    
    };
}